/* eslint-disable-next-line no-unused-vars */
const samples = [
  'There was no possibility of taking a walk that day. We had been wandering, indeed, in the leafless shrubbery an hour in the morning; but since dinner (Mrs. Reed, when there was no company, dined early) the cold winter wind had brought with it clouds so sombre, and a rain so penetrating, that further out-door exercise was now out of the question.',
  'Solemnly he came forward and mounted the round gunrest. He faced about and blessed gravely thrice the tower, the surrounding land and the awaking mountains. Then, catching sight of Stephen Dedalus, he bent towards him and made rapid crosses in the air, gurgling in his throat and shaking his head. Stephen Dedalus, displeased and sleepy, leaned his arms on the top of the staircase and looked coldly at the shaking gurgling face that blessed him, equine in its length, and at the light untonsured hair, grained and hued like pale oak.',
  'On the first Monday of the month of April, 1625, the bourg of Meung, in which the author of the Romance of the Rose was born, appeared to be in as perfect a state of revolution as if the Huguenots had just made a second Rochelle of it. Many citizens, seeing the women flying towards the High Street, leaving their children crying at the open doors, hastened to don the cuirass, and, supporting their somewhat uncertain courage with a musket or a partizan, directed their steps towards the hostelry of the Franc Meunier, before which was gathered, increasing every minute, a compact group, vociferous and full of curiosity.',
  'Mr Phileas Fogg lived, in 1872, at No. 7, Saville Row, Burlington Gardens, the house in which Sheridan died in 1814. He was one of the most noticeable members of the Reform Club, though he seemed always to avoid attracting attention; an enigmatical personage, about whom little was known, except that he was a polished man of the world. People said that he resembled Byron, - at least that his head was Byronic; but he was a bearded, tranquil Byron, who might live on a thousand years without growing old.',
  'I am by birth a Genevese, and my family is one of the most distinguished of that republic. My ancestors had been for many years counsellors and syndics, and my father had filled several public situations with honour and reputation. He was respected by all who knew him for his integrity and indefatigable attention to public business. He passed his younger days perpetually occupied by the affairs of his country; a variety of circumstances had prevented his marrying early, nor was it until the decline of life that he became a husband and the father of a family.',
  'Whether I shall turn out to be the hero of my own life, or whether that station will be held by anybody else, these pages must show. To begin my life with the beginning of my life, I record that I was born (as I have been informed and believe) on a Friday, at twelve o\'clock at night. It was remarked that the clock began to strike, and I began to cry, simultaneously.'
]
